### PR TITLE
⚔ Fix #173: Ignore when a component enables itself twice without swit…

### LINKED ISSUE #173: [QUESTION/BUG?] Duplicate focus tree IDs cause keypresses to be ignored
**Describe the bug**
This might or might not be a bug in `react-hotkeys`. I'm currently working to create a minimal example that reproduces this issue, but it's possible that it's caused by some complex interactions in my application that can't be trivially reproduced.

However, in lieu of finding the exact cause, I've managed to track down the effect, and a possible fix.

I have one parent `HotKeys` component near the root of the application and one child `HotKeys` nested in it. Certain interactions in my application result in a duplicate focus tree ID being added to the `_focusTreeIds` queue for the outer `HotKeys`. When this occurs, the first keypress after clicking on the inner hotkeys will be ignored with a message like

    Ignored 'a' keydown event because it had an old focus tree id: 1.

I've included a log below showing this behavior. I added some additional logging statements in a [fork](https://github.com/Chris-Slade/react-hotkeys/commit/5ed5a5770373546337ce52a1ed90f87421461185) to demonstrate what's happening; the output from these statements is included in the log below. (Note that the line numbers correspond to the forked versions of the files. The linked commit is the only change made in this fork.)

Modifying `withHotKeys.js` only to queue a new focus tree ID if it's different from the previous one (see the commented out lines [here](https://github.com/Chris-Slade/react-hotkeys/commit/5ed5a5770373546337ce52a1ed90f87421461185#diff-e06e6542b29a90436fe0dda49b41f193R216)) prevents this "bug" from manifesting, but I'm not sure if this fix is correct.

If it is some form of misuse that causes it, would it make sense to protect against it in this way?

**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys etc)**
See above.

**Expected behavior**
Not sure.

**Platform (please complete the following information):**
- Version: Tried with 2.0.0-pre5. I also linked in development builds of the library when debugging this, testing with versions 2.0.0-pre5 and b866ec15.
- Browser: Electron ^4.1.4 (Chromium 69.0.3497.128)
- OS: macOS (10.14.4) and Windows 10.

**Are you willing and able to create a PR request to fix this issue?**
Yes, if the proposed fix makes sense. Otherwise, maybe.

**Include the smallest log that includes your issue:**
```
withHotKeys.js:114 Rendering HotKeys component 0
withHotKeys.js:114 Rendering HotKeys component 1
withHotKeys.js:227 Handling focus (component ID: 0, is focused: undefined)
FocusOnlyKeyEventStrategy.js:209 HotKeys (F0📕-C0🔺-P0🔺:) Focused. 
withHotKeys.js:175 Focus tree IDs (after push): [0]
withHotKeys.js:114 Rendering HotKeys component 0
FocusOnlyKeyEventStrategy.js:248 HotKeys (F0📕-C0🔺-P0🔺:) Received new props.
withHotKeys.js:259 Handling blur (component ID: 0, is focused: true)
FocusOnlyKeyEventStrategy.js:280 HotKeys (F0📕-C0🔺-P0🔺:) Lost focus.
withHotKeys.js:183 Focus tree IDs (after shift): []
withHotKeys.js:227 Handling focus (component ID: 0, is focused: false)
FocusOnlyKeyEventStrategy.js:209 HotKeys (F1📗-C0🔺-P0🔺:) Focused. 
withHotKeys.js:175 Focus tree IDs (after push): [1]
withHotKeys.js:227 Handling focus (component ID: 0, is focused: true)
FocusOnlyKeyEventStrategy.js:209 HotKeys (F1📗-C0🔺-P1⭐️:) Focused. 
withHotKeys.js:175 Focus tree IDs (after push): (2) [1, 1]
ActivityWindow.tsx:164 Focusing ActivityWindow
withHotKeys.js:259 Handling blur (component ID: 0, is focused: true)
FocusOnlyKeyEventStrategy.js:280 HotKeys (F1📗-C0🔺-P1⭐️:) Lost focus.
withHotKeys.js:183 Focus tree IDs (after shift): [1]
withHotKeys.js:227 Handling focus (component ID: 1, is focused: undefined)
FocusOnlyKeyEventStrategy.js:209 HotKeys (F2📘-C1⭐️-P0🔺:) Focused. 
withHotKeys.js:175 Focus tree IDs (after push): [2]
withHotKeys.js:227 Handling focus (component ID: 0, is focused: false)
FocusOnlyKeyEventStrategy.js:209 HotKeys (F2📘-C0🔺-P1⭐️:) Focused. 
withHotKeys.js:175 Focus tree IDs (after push): (2) [1, 2]
FocusOnlyKeyEventStrategy.js:320 HotKeys (F2📘-E0❤️-C0🔺-P1⭐️:) Ignored 'a' keydown event because it had an old focus tree id: 1.
FocusOnlyKeyEventStrategy.js:669 HotKeys (F2📘-E0❤️-C0🔺-P1⭐️:) Stopping further event propagation.
withHotKeys.js:183 Focus tree IDs (after shift): [2]
FocusOnlyKeyEventStrategy.js:377 HotKeys (F2📘-E1💚-C0🔺-P1⭐️:) New 'a' keyup event.
```

This is with log level `debug`. The `verbose` log is too long to include here.

**What Configuration options are you using?**

None, other than `logLevel`.

### PR DESCRIPTION
**Pull request by greena13**
# Context

For reasons that are still a mystery to me, it seems a component (at least from the perspective of `react-hotkeys`) can focus itself twice in a row, without changing focus trees. This results in the list of focus trees the component is a part of being incorrectly maintained, leading to #173.

# This pull request

Adds the conditional logic to check if a `componentId` has already been registered, aborting if an existing component options is already found in the registry. If so, it returns `undefined` rather than the current focus tree id - and `HotKeys` has been updated to not add this to its list of focus Ids (and ignore it).

### CODE REVIEW

File: src/lib/strategies/FocusOnlyKeyEventStrategy.js [hunk 1]
```diff
@@ -145,9 +145,9 @@ class FocusOnlyKeyEventStrategy extends AbstractKeyEventStrategy {
    * @param {HandlersMap} actionNameToHandlersMap - Map of actions to handler functions
    * @param {Object} options Hash of options that configure how the actions
    *        and handlers are associated and called.
-   * @returns {[FocusTreeId, ComponentId]} The current focus tree's ID and a unique
-   *         component ID to assign to the focused HotKeys component and passed back
-   *         when handling a key event
+   * @returns {FocusTreeId|undefined} The current focus tree's ID or undefined if the
```
Comment (greena13) [inline src/lib/strategies/FocusOnlyKeyEventStrategy.js]: 🐥 📚 Fixes stale documentation reporting the correct return type & adds a description of when the function will return `undefined`.
