### PR TITLE
Fix typings

### LINKED ISSUE #84: Add `ClassName` to interface props [Typescript]
Currently this is ended up with an error
```
<HotKeys className={baseClass} keyMap={keyMap} ...
```

But it will be rendered totally fine
```
<div tabindex="-1" class="example_class"...
```

It's quite useful to have control over the `:focus` pseudo class based on a simple class.

### PR DESCRIPTION
**Pull request by matthew-matvei**
This pull request aims to resolve #84 

I have tested this by developing and `npm pack`ing locally, then installing the package into my [FreeMAN](https://github.com/matthew-matvei/freeman) app which uses `react-hotkeys` fairly extensively.

- Importing `FocusTrap` (resolved `ts` errors, though actual type definitions instead of 'importing' js file for this class might be best moving forward)
- Removed initialisers in `interface` definitions
- Made handler function `keyEvent` optional, since the API doesn't seem to require it
- `HotKeysProps` extends React's `Props<HotKeys>` in order to get in-built props like `ref` and `children`

I don't think this project is set up for any automated type tests or `tslint`ing, so I would suggest anyone interested to build this branch locally, `npm pack` and install it into where you are consuming it. I'm aware my own `tsconfig.json` could potentially make this solution not work for you.

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -1,12 +1,13 @@
...
+import FocusTrap from './lib/FocusTrap';
 
 type MouseTrapKeySequence = string | Array<string>;
 
 type KeyEventName = 'keyup' | 'keydown' | 'keypress';
 
 interface KeyMapOptions {
   sequence: MouseTrapKeySequence;
-  action: KeyEventName = 'keypress';
+  action: KeyEventName;
```
Comment (greena13) [inline index.d.ts]: I was under the impression what was there before was setting the default value to `keypress` (if not specified, the package behaves as if the `'keypress'` value was passed). Am I wrong in this?

File: index.d.ts [hunk 2]
```diff
@@ -26,23 +27,18 @@ interface HotKeysProps extends FocusTrapProps<HotKeys> {
   /**
    * A mapping of action names to handler functions
    */
-  handlers?: { [key: string]: (keyEvent: KeyboardEvent) => void };
+  handlers?: { [key: string]: (keyEvent?: KeyboardEvent) => void };
```
Comment (greena13) [inline index.d.ts]: Thanks, this was an oversight on my part. The `keyEvent` is indeed optionally accepted by the handler.

File: index.d.ts (hunk 1 above)
Comment (matthew-matvei) [reply index.d.ts]: I don't believe so. Typescript is about definitions, not about action. Once transpiled, it's all just javascript and these interfaces won't even exist in your output. Maybe it'll be a future language feature?

You can set default values of function parameters (so long as the default is a literal of some sort), so maybe you're confusing it with that?

File: index.d.ts (hunk 2 above)
Comment (matthew-matvei) [reply index.d.ts]: That's cool, I don't even think I was aware of that, I'll be able to do some refactoring in my own project with that knowledge.

Is that documented? All the examples I saw used parameterless handler functions

File: index.d.ts [hunk 3]
```diff
@@ -17,7 +18,7 @@ interface FocusTrapProps extends React.HTMLProps<FocusTrap> {
   component?: React.Component | string;
 }
 
-interface HotKeysProps extends FocusTrapProps<HotKeys> {
+interface HotKeysProps extends React.Props<HotKeys>, FocusTrapProps {
```
Comment (greena13) [inline index.d.ts]: Was the problem that `HotKeyProps` wasn't correctly inheriting `React.HTMLProps` through `FocusTrapProps`, or that `React.HTMLProps` is not correct (doesn't contain `className`), but `React.Props` is?

File: index.d.ts (hunk 1 above)
Comment (greena13) [reply index.d.ts]: Ah I see, yes I seem to have been mis-interpretting syntax that works for functional parameters and object literals as also being applicable for interfaces.

File: index.d.ts (hunk 2 above)
Comment (greena13) [reply index.d.ts]: Maybe, I am mis-understanding you? All of the [examples for defining handlers](https://github.com/greena13/react-hotkeys#defining-handlers) accept the `KeyboardEvent` object.

Comment (matthew-matvei) [reply index.d.ts]: I'm looking in the `/master/index.js` file and not seeing them. But maybe I'm blind :-)

File: index.d.ts (hunk 3 above)
Comment (matthew-matvei) [reply index.d.ts]: I would have to tinker about again to figure out exactly what the deal is with `className`. From memory it was happy once I added the second import, but I could be misremembering.

Somewhere along the lines you'll need `React.Props` to get the three in-built props, one of which I needed in my project

Comment (greena13) [reply index.d.ts]: Can we try using `React.HTMLAttributes`? It seems [React.Props has been deprecated](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8509#issuecomment-197073806)

Comment (matthew-matvei) [reply index.d.ts]: Using `React.HTMLAttributes`. I had to create definitions for `onFocus` and `onBlur` since your use of them seems to override React's own

File: index.d.ts [hunk 4]
```diff
@@ -1,23 +1,24 @@
 import * as React from 'react';
+import FocusTrap from './lib/FocusTrap';
```
Comment (greena13) [inline index.d.ts]: I've just noticed this after merging. I *think* this may need to be `./es/FocusTrap` (`./lib` is not included in the published npm module).

I'll make the change, unless you enlighten me about something I am misunderstanding.

Comment (matthew-matvei) [reply index.d.ts]: I made the import since I had a compiler warning about `FocusTrap` not being imported, but I don't think any real typings would be coming from it (there would need to be a `FocusTrap.d.ts` file to import I suppose

In any case, there's no runtime with these files, it won't end up in generated code, there's no real import. Shouldn't break anything. But it's up to you, obviously :-)

Comment (mykter) [reply index.d.ts]: FYI currently 1.0.5 is reporting:
```
react-hotkeys/index.d.ts(2,23): error TS7016: Could not find a declaration file for module './cjs/FocusTrap'. './node_modules/react-hotkeys/cjs/FocusTrap.js' implicitly has an 'any' type.
```

Comment (greena13) [reply index.d.ts]: Thanks for taking the time to report, @mykter. It seems like we can't get away with importing a file that doesn't exist. I'll take a look at this.

Comment (matthew-matvei) [reply index.d.ts]: Any more info about your setup? This installed fine for me locally (`npm pack`ing in this project and installing to another). Note that neither `lib/FocusTrap.js` nor `cjs/FocusTrap.cjs` have any typing info.

I can return to this after the easter weekend

Comment (greena13) [reply index.d.ts]: This was also reported as a [separate issue](https://github.com/greena13/react-hotkeys/issues/89). Seems to occur when `noImplicityAny` is enabled in `tsconfig.json`. 

I've released [v1.0.6](https://github.com/greena13/react-hotkeys/commit/4478bdbda1b6788395d40f08a94151cc098dacbc), which I hope has resolved the issue.

Comment (mykter) [reply index.d.ts]: I use "strict": true, which includes noImplicitAny.
1.0.6 does indeed address it :+1:

Comment (matthew-matvei) [reply index.d.ts]: Very odd, I use `noImplicitAny`on the testing project
