### PR TITLE
🐛 Fix #183: Add separate dictionary of keys that cmd hides the keyup …

### LINKED ISSUE #183: [BUG] Handler triggers without completing full sequence - 2.0.0-pre5
**Describe the bug**
meta keys trigger events even when full sequence of keys has not been completed

Here's a sandbox of the issue: https://codesandbox.io/s/gracious-dhawan-3ncnw?fontsize=14

To reproduce, focus the input, then do the following:
1. type 'command+enter' (this should trigger the log)
2. type 'command' (this triggers the log but should not)

**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys etc)**
HotKeys

**Expected behavior**
action only triggers when full sequence of keys is completed

**Platform (please complete the following information):**
 - Version of react-hotkeys: 2.0.0-pre5
 - Browser: brave browser (a flavor of chrome)
 - OS: MacOS 10.14.5

**Are you willing and able to create a PR request to fix this issue?**
Maybe!

**APPLICABLE TO v2.0.0-pre1 AND ABOVE: ======================**

**Include the smallest log that includes your issue:**
```
HotKeys (F0📕-E14💙-C0🔺-P0🔺:) Ignored 'Enter+Meta' keypress because it doesn't have any keypress handlers.
breadcrumbs.js:58 HotKeys (GLOBAL-E14💙): Received (simulated) 'Meta' keypress event (that has already passed through React app).
breadcrumbs.js:58 HotKeys (GLOBAL-E14💙): Key history: [
    {
        "keys": {
            "Enter": [
                [
                    true,
                    false,
                    false
                ],
                [
                    true,
                    true,
                    false
                ]
            ],
            "Meta": [
                [
                    true,
                    true,
                    false
                ],
                [
                    true,
                    true,
                    true
                ]
            ]
        },
        "ids": [
            "Enter+Meta"
        ],
        "keyAliases": {}
    },
    {
        "keys": {
            "Enter": [
                [
                    true,
                    false,
                    false
                ],
                [
                    true,
                    true,
                    false
                ]
            ],
            "Meta": [
                [
                    true,
                    false,
                    false
                ],
                [
                    true,
                    true,
                    false
                ]
            ]
        },
        "ids": [
            "Enter+Meta"
        ],
        "keyAliases": {}
    }
].
breadcrumbs.js:58 HotKeys (GLOBAL-E14💙): Ignored 'Enter+Meta' keypress because it doesn't have any keypress handlers.
breadcrumbs.js:58 HotKeys (F0📕-E15💛-C0🔺-P0🔺:) New 'Meta' keyup event.
breadcrumbs.js:58 HotKeys (F0📕-E15💛-C0🔺-P0🔺:) Key history: [
    {
        "keys": {
            "Enter": [
                [
                    true,
                    false,
                    false
                ],
                [
                    true,
                    true,
                    false
                ]
            ],
            "Meta": [
                [
                    true,
                    true,
                    true
                ],
                [
                    true,
                    true,
                    true
                ]
            ]
        },
        "ids": [
            "Enter+Meta"
        ],
        "keyAliases": {}
    },
    {
        "keys": {
            "Enter": [
                [
                    true,
                    false,
                    false
                ],
                [
                    true,
                    true,
                    false
                ]
            ],
            "Meta": [
                [
                    true,
                    true,
                    true
                ],
                [
                    true,
                    true,
                    true
                ]
            ]
        },
        "ids": [
            "Enter+Meta"
        ],
        "keyAliases": {}
    }
].
breadcrumbs.js:58 HotKeys (F0📕-E15💛-C0🔺-P0🔺:) Ignored 'Enter+Meta' keyup because it doesn't have any keyup handlers.
breadcrumbs.js:58 HotKeys (GLOBAL-E15💛): Received 'Meta' keyup event (that has already passed through React app).
breadcrumbs.js:58 HotKeys (GLOBAL-E15💛): Key history: [
    {
        "keys": {
            "Enter": [
                [
                    true,
                    false,
                    false
                ],
                [
                    true,
                    true,
                    false
                ]
            ],
            "Meta": [
                [
                    true,
                    true,
                    false
                ],
                [
                    true,
                    true,
                    true
                ]
            ]
        },
        "ids": [
            "Enter+Meta"
        ],
        "keyAliases": {}
    },
    {
        "keys": {
            "Enter": [
                [
                    true,
                    false,
                    false
                ],
                [
                    true,
                    true,
                    false
                ]
            ],
            "Meta": [
                [
                    true,
                    true,
                    false
                ],
                [
                    true,
                    true,
                    true
                ]
            ]
        },
        "ids": [
            "Enter+Meta"
        ],
        "keyAliases": {}
    }
].
breadcrumbs.js:58 HotKeys (GLOBAL-E15💛): Ignored 'Enter+Meta' keyup because it doesn't have any keyup handlers.
```

**What Configuration options are you using?**
None!

### PR DESCRIPTION
**Pull request by greena13**
# Context

`react-hotkeys` simulates some key events the browser does not trigger itself, to avoid users of `react-hotkeys` from having to think about which events are natively supported or not. One of the events that `react-hotkeys` simulates is the `keyup` event in key combinations involving the `cmd` key (e.g. `cmd+a`). 

Some keys when pressed with `cmd` still trigger their own `keyup` event, but there is a list of keys that do not. Currently `react-hotkeys` re-uses the list of keys that do not have their own `keypress` event to determine whether it should also simulate the `keyup` event. This list is incorrect and results on some `keyup` events not being simulated, and `react-hotkeys` still behaving as if they are still held down (#183).

# This pull request

* Creates a separate (correct) list, to keep track of the keys that do not natively trigger a `keyup` event when pressed with `cmd` (`Meta`).

### CODE REVIEW

File: src/const/KeysWithKeyupHiddenByCmd.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ */
+const KeysWithKeyupHiddenByCmd = {
+  Enter: true,
+  Backspace: true,
+  ArrowRight: true,
+  ArrowLeft: true,
+  ArrowUp: true,
+  ArrowDown: true,
+  /**
+   * Caps lock is a strange case where it not only does not have a key press event,
```
Comment (greena13) [inline src/const/KeysWithKeyupHiddenByCmd.js]: ⬜️ 📚 Update this comment to refer to a `key up` event, not a `key press` one.
