### PR TITLE
🐛 Fix #150: Reset global handler resolution state when a new GlobalHo…

### LINKED ISSUE #150: [BUG] Global hotkeys throwing errors after dom changes
**Describe the bug**
When using the GlobalHotKeys component it gives errors after some components mount and unmount.
using any keys seems to give the following error even though the hotkeys are still working and actions are triggering as usual:
image

**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys etc)**
GlobalHotKeys
****
**Expected behavior**
it should not error out. 

**Platform (please complete the following information):**
 - Version of react-hotkeys v2 prerelease 4
 - Browser chrome
 - OS: [windows, macos]

**Are you willing and able to create a PR request to fix this issue?**
I did a quick dive and by adding `  || []` at the end of this [line](https://github.com/greena13/react-hotkeys/blob/eb4163383a9680f52ca768ea32ba7e18f354bd90/src/lib/strategies/AbstractKeyEventStrategy.js#L719), simply solves the issue in our usecase. not sure if this fix is right or if any deeper changes are needed

**APPLICABLE TO v2.0.0-pre1 AND ABOVE: ======================**

**Include the smallest log that includes your issue:**

Types seem to be broken so I couldn't import the configure function

### PR DESCRIPTION
**Pull request by greena13**
# Context

#150 documents that when a `GlobalHotKeys` component is mounted, unmounted and then re-mounted, it does not reset the handler resolution state on the second mount (even though the configuration of `GlobalHotKeys` that it should be using to resolve the handlers has changed).

This issue would likely also arise in a number of other situations where `GlobalHotKeys` components were being unmounted and remounted or updated - but the situation above is probably the simplest case.

Thanks to the investigation of @StephenHaney and the pull request of @mrlubos (#157) the solution of resetting the handle resolution state every time a new `GlobalHotKeys` component mounted, presented itself.

# This pull request

Simply adds the change suggested above, and resets the handler resolution state whenever a new `GlobalHotKeys` component mounts. 

This is a relatively light-weight operation, as when multiple `GlobalHotKeys` components are mounting (and the user is not yet pressing any keys) we are effectively clearing empty objects, anyway.

A test has been added that correctly reported the failure condition, and is now passing.

### CODE REVIEW

File: src/lib/strategies/GlobalKeyEventStrategy.js [hunk 1]
```diff
@@ -73,6 +73,8 @@ class GlobalKeyEventStrategy extends AbstractKeyEventStrategy {
 
     this._updateDocumentHandlers();
 
+    this._initHandlerResolutionState();
```
Comment (greena13) [inline src/lib/strategies/GlobalKeyEventStrategy.js]: ⬜️⚔️Check the behaviour of `this._updateDocumentHandlers()` to make sure calling these methods in this sequence will always work as intended.

Comment (greena13) [reply src/lib/strategies/GlobalKeyEventStrategy.js]: ⬜️ 🚀See if there is a way of wrapping the resetting of state in `this._initHandlerResolutionState()` in a condition that will abort resetting the state if it's apparent handler resolution hasn't actually taken place yet, and the state is already set to the default values.
